settings:
  title: 'Status Page'
  url: 'https://status.o6.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: get-gre4a.1i.workers.dev # unique identifier
    name: GET gre4a.1i.workers.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://gre4a.1i.workers.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: post-gre4a.1i.workers.dev # unique identifier
    name: POST gre4a.1i.workers.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://gre4a.1i.workers.dev/' # URL to fetch
    method: POST # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: get-wpdemo.jplhomer.org
    name: GET wpdemo.jplhomer.org
    description: 'Built for anything connected to the Internet.'
    url: 'https://wpdemo.jplhomer.org/wp-json/wp/v2/posts'
    method: GET
    expectStatus: 200

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
