name = "status"
workers_dev = true
account_id = "1c5f0bb50c92188dd028fa501cb54b88"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]


